name: rio
version: 0.0.3.0
synopsis: A standard library for Haskell
description: See README and Haddocks at <https://www.stackage.org/package/rio>
license: MIT
author: Michael Snoyman
maintainer: michael@snoyman.com
github: commercialhaskell/rio
category: Control
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.9 && < 10
- bytestring
- containers
- deepseq
- directory
- exceptions # FIXME what do we do with MonadThrow?
- filepath
- hashable
- microlens
- mtl
- primitive
- text
- time
- typed-process >= 0.2.1.0
- unliftio >= 0.2.6.0
- unordered-containers
- vector

# Just for preprocessor directives
- process

when:
- condition: os(windows)
  then:
    cpp-options: -DWINDOWS
    dependencies:
    - Win32
  else:
    dependencies:
    - unix

library:
  source-dirs: src/

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - rio
    - hspec
